set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on

setw -g mode-keys vi

set -g status-bg '#333333'
set -g status-fg '#d17e3e'

bind-key r command-prompt -I "#W" "rename-window '%%'"

# tmux-resurrect plugin (leader + ctrl + s = saves and leader + ctrl + r = restores)
run-shell /home/tobias/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
