#!/bin/bash

BROWSER="librewolf"  
# Paths
FAVORITES_FILE="$HOME/.config/rofi/favorites.txt"
#HISTORY_FILE="$HOME/.config/rofi/history.txt" <- this feature is unused for the time being
#MAX_HISTORY=50

# URL-encode function, encodes white spaces or charactes like ?, #, etc into hex 
# exmaple: hello world -> hello%20world
urlencode() {
    local string="${1}"
    local strlen=${#string}
    local encoded=""
    local pos c o

    for (( pos=0 ; pos<strlen ; pos++ )); do
        c=${string:$pos:1}
        case "$c" in
            [-_.~a-zA-Z0-9]) o="${c}" ;;
            *) printf -v o '%%%02x' "'$c" ;;
        esac
        encoded+="${o}"
    done
    echo "${encoded}"
}

# lets you use multiples quer's: Ex: gi cat,duck, plato
multi_search() {
    local command=$1
    local query=$2
    IFS=',' read -ra terms <<< "$query"
    
    # Define URL patterns
    declare -A url_patterns=(
	# Search Engines
        [g]="https://www.google.com/search?q="
        [gi]="https://www.google.com/search?tbm=isch&q="
        [d]="https://duckduckgo.com/?q="
        [di]="https://duckduckgo.com/?q=SEARCH&ia=images&iax=images"
	# Dictionaries
        [wrd]="https://www.wordreference.com/definition/"
        [wrds]="https://www.wordreference.com/definicion/"
        [wrets]="https://www.wordreference.com/es/translation.asp?tranword="
        [wrste]="https://www.wordreference.com/es/en/translation.asp?spen="
        [wrjte]="https://www.wordreference.com/jaen/"
        [wretj]="https://www.wordreference.com/enja/"
	# Misc
        [yt]="https://www.youtube.com/results?search_query="
	      [pdf]="https://www.google.com/search?q=SEARCH+site%3Apdfcoffee.com"
        [book]="https://es.annas-archive.gl/search?q="
        [box]="https://letterboxd.com/search/"
        [rym]="https://rateyourmusic.com/search?searchterm=SEARCH&searchtype="
        [mal]="https://myanimelist.net/search/all?q="
        [arch]="https://www.google.com/search?q=SEARCH+site%3Awiki.archlinux.org"
        [sheet]="https://musescore.com/sheetmusic?text="
    )

    for term in "${terms[@]}"; do
        term="${term#"${term%%[![:space:]]*}"}"  # remove leading whitespace
        term="${term%"${term##*[![:space:]]}"}"  # remove trailing whitespace
        [ -z "$term" ] && continue 

        encoded_term=$(urlencode "$term")

    pattern="${url_patterns[$command]}"
	  if [[ "$pattern" == *SEARCH* ]]; then
        	url="${pattern//SEARCH/$encoded_term}"
	  else
        	url="${pattern}${encoded_term}"  # For patterns without SEARCH placeholder
	  fi
        "$BROWSER" "--new-tab" "$url"
    done
}

# For the "?" command
commands="f - Search favorite URLs
c - clipboard
+|calc - rofi-calc
sh - run shell command
g, d - Search engines
gi, di - Search images
wrd - English Definition
wrds - Spanish Definition
wrets - English to Spanish
pdf - site:pdfcoffee.com
book|annas - annas-archive
sheet - musescore
mal - myanimelist
rym - rateyourmusic
arch - site:wiki.archlinux.org
"

# Main input
input=$(rofi -dmenu -p ":" \
        -font "JetBrains Mono Nerd Font 20" \
        -theme-str '*{ background: #2E3440; text-color: #D8DEE9; } listview { lines: 0; } entry { placeholder: ""; } scrollbar { width: 0; }')

# Handle empty input
[ -z "$input" ] && exit 0

case $input in
# Search Engines
    g\ *) multi_search "g" "${input#g }" ;;
    gi\ *) multi_search "gi" "${input#gi }" ;;
    d\ *) multi_search "d" "${input#d }" ;;
    di\ *) multi_search "di" "${input#di }" ;;
    
# Dictionary
    wrd\ *) multi_search "wrd" "${input#wrd }" ;;
    wrds\ *) multi_search "wrds" "${input#wrds }" ;;
    wrets\ *) multi_search "wrets" "${input#wrets }" ;;
    wrste\ *) multi_search "wrste" "${input#wrste }" ;;
    wrjte\ *) multi_search "wrjte" "${input#wrjte }" ;;
    wretj\ *) multi_search "wretj" "${input#wretj }" ;;

  pr\ *) # WORD + Pronunciation
    query="${input#pr }"
    $BROWSER --new-tab "https://duckduckgo.com/?q=${query}+pronunciation"
    ;;  

#Other utilities   
    yt\ *) multi_search "yt" "${input#yt }" ;;
    pdf\ *) multi_search "pdf" "${input#pdf }" ;; # Search google with site:pdfcoffee.com 
    annas\ * | book\ *) multi_search "book" "${input#* }" ;; # Search annas-archive
    arch\ *) multi_search "arch" "${input#arch}";; # Search google with site:wiki.archlinux.org
    sheet\ *) multi_search "sheet" "${input#sheet}" ;; # Search musescore sheet music
    mal\ *) multi_search "mal" "${input#mal}" ;;# Search myanimelis.net
    movie\ * | box\ *) multi_search "box" "${input#* }" ;; # Search letterboxd
    rym\ *) multi_search "rym" "${input#rym}" ;;  # Search rateyourmusic

  np*) #newtab personal-start-up-page i made
    $BROWSER --new-tab "https://isud32.github.io/personal-start-up-page/" 
    ;;
  nt*) # newtab
    $BROWSER --new-tab ""
     ;;
# Utilities - not web related

 sh\ *) # Run system command 
    command="${input#sh}"
    alacritty -e zsh -c "${command}; exec zsh"
    ;;

  f|f\ *)
        selected=$(awk -F' - ' '{print $1}' "$FAVORITES_FILE" | \
            rofi -dmenu -p " Favorites:" -font "JetBrains Mono Nerd Font 20" -multi-select)
        
        if [ -n "$selected" ]; then
            while read -r line; do
                url=$(awk -F' - ' -v s="$line" '$1 == s {print $2}' "$FAVORITES_FILE")
                [ -n "$url" ] && "$BROWSER" "--new-tab" "$url"
            done <<< "$selected"
        fi
        ;;  \?|\?\ *)
        # Open "cheatsheet"  
        echo "$commands" | rofi -dmenu -p "Cheatsheet >:)" -font "JetBrains Mono Nerd Font 20" -i -icons "false"
        "$0"
    ;;

  c|cl|cl\ *)
    rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
    ;; 
  +|calc|calc\ *)
    rofi -show calc -modi calc -no-show-match -no-sort
    ;;

  *) # Default case with error handling
    ( rofi -e "Unknown command: ${input}" -font "JetBrains Mono Nerd Font 20" & )
    ;;
  esac
