#!/bin/bash
# This is just to run ps2 emulator and a japanese popup dictionary with OCR 
echo "がんばれ！！"
"$HOME/Programs/pcsx2.AppImage" > /tmp/pcsx2.log 2>&1 &
(
    cd "$HOME/Programs/meikipop" || exit 1
    ./meikipop 
)
