#!/bin/sh

curr_brightness=$(cat /sys/class/backlight/amdgpu_bl1/brightness)
max_brightness=$(cat /sys/class/backlight/amdgpu_bl1/max_brightness)

brightness_per=$(( (100 * curr_brightness + max_brightness / 2) / max_brightness ))

echo "󰃠 ${brightness_per}% "
